create section with basic styles
andreasrukom19/team-project-group14 pull request #3
Opened 2023-08-11 09:23 UTC by HannaSydoruk

2023-08-11 13:33 UTC, andreasrukom19 requested changes
Все добре. Але у всіх секціях контент повинен бути обгорнутий у div.container

2023-08-11 13:41 UTC, andreasrukom19 reviewed
Потрібне доопрацювання

2023-08-12 10:11 UTC, andreasrukom19 requested changes

2023-08-12 10:11 UTC, andreasrukom19 commented on src/css/price.css
> +  padding: 64px 16px;
Скоріш за все `padding-bottom: 64px` тут не потрібен. Так як у наступної секції повинен бути padding-top: 64px

2023-08-12 10:11 UTC, andreasrukom19 commented on src/css/price.css
> +  text-transform: uppercase;
Треба обсудити font-family. Шрифти то підключені у index.html, але ж для body глобально нічого не прописано

2023-08-12 10:11 UTC, andreasrukom19 commented on src/css/price.css
> +    margin: auto;
Повинно бути `margin: 0 auto`

2023-08-12 10:11 UTC, andreasrukom19 commented on src/css/price.css
> +    padding: 100px 32px;
Знову ж таки, нижній padding не ставимо

2023-08-12 10:11 UTC, andreasrukom19 commented on src/css/price.css
> +    max-width: 1096px;
Повинно бути max-width: 1440px;

2023-08-12 10:11 UTC, andreasrukom19 commented on src/css/price.css
> +    padding: 100px 172px;
padding-bottom не потрібний

2023-08-12 13:51 UTC, andreasrukom19 requested changes

2023-08-12 13:51 UTC, andreasrukom19 commented on src/css/price.css
> +  box-sizing: border-box;
До проекту підключений normalise. Так що box-sizing там прописаний

2023-08-12 13:51 UTC, andreasrukom19 commented on src/css/price.css
> +  box-sizing: border-box;
Аналогічно, box-sizing не потрібний

2023-08-12 14:03 UTC, HannaSydoruk commented on src/css/price.css
> +  box-sizing: border-box;
Андрію, виправила по зауваженням - згодна в принципі. шрифт поки залишила, тому що у боді його не прописано, також якщо перенесеться в загарльні стилі visually-hidden, його теж можна буде прибрати з локальних стилів. але поки залишаю

2023-08-13 09:42 UTC, andreasrukom19 requested changes

2023-08-13 09:42 UTC, andreasrukom19 commented on src/css/price.css
> +  width: 100%;
Потрібно видалити

2023-08-13 09:42 UTC, andreasrukom19 commented on src/css/price.css
> +  padding: 64px 16px 0 16px;
Тільки padding-top: 64px

2023-08-13 09:42 UTC, andreasrukom19 commented on src/css/price.css
> +}
Властивості для  visually-hidden будуть прописані в загальному файлі стилів. Потрібно буде видалити

2023-08-13 09:42 UTC, andreasrukom19 commented on src/css/price.css
> +  font-family: Roboto;
font-family прописаний для body в загальному файлі.

2023-08-13 09:42 UTC, andreasrukom19 commented on src/css/price.css
> +}
Даний медіазапит не потрібний

2023-08-13 09:42 UTC, andreasrukom19 commented on src/css/price.css
> +  }
Тільки padding-top: 100px; Я б ці відступи взагалі задавав би секціям (верхній паддінг)

2023-08-13 09:42 UTC, andreasrukom19 commented on src/css/price.css
> +    padding: 100px 172px 0 172px;
Те саме. padding-top: 100px;

2023-08-13 10:54 UTC, HannaSydoruk commented on src/css/price.css
> +    padding: 100px 172px 0 172px;
тут залишаю padding: 100px 172px 0 172px; тому що секція вужча, ніж більшість інших

2023-08-13 15:43 UTC, andreasrukom19 approved these changes

2023-08-13 15:44 UTC, merged